# This file was generated by				
# Qfsm Version 0.53					
# (C) Stefan Duffner, Rainer Strobel			


%%{
machine FSMUSPatentAct;

main :=
start:
s1: (
  [b] @s2  -> s2 | 
  [a] @s3  -> s3 | 
  [^a-b|] @s1  -> s1),
s2: (
  [c] @s3  -> s3),
s3: (
  [d] @s5  -> s5 | 
  [e] @s4  -> s4),
s5: (
  "" @s5 -> final),
s4: (
  [f] @s5  -> s5 | 
  [g] @s6  -> s6),
s6: (
  "" @s6 -> final);

}%%
