# This file was generated by				
# Qfsm Version 0.53					
# (C) Stefan Duffner, Rainer Strobel			


%%{
machine FSMCDNPatentAct;

main :=
start:
IdeaND: (
  [b] @s2  -> IdeaD | 
  [a] @s3  -> CDNAppConf | 
  [^a-b|] @s1  -> IdeaND),
IdeaD: (
  [c] @s3  -> CDNAppConf),
CDNAppConf: (
  "" @s3 -> final);

}%%
